#Define Service Name and Provider
service: 
  name: CPEmailTask
provider:
  name: aws
  runtime: python3.7

#Define function
functions:
  CPEmailTask:
    handler: main.lambda_handler
    events:
    - http:
        path: main.lambda_handler
        method: ANY 
    environment:
      MGMTHOSTNAME: REPLACE.MGMTHOSTNAME
      PASSWORD: REPLACE.TASK_PASSWORD
      USER: REPLACE.USER
      SNS_ARN: !Ref SNSTopic
      

#Define SNS Topic        
resources:
  Resources:
    SNSTopic:
       Type: AWS::SNS::Topic
       Properties:
         DisplayName: CPEmailTask
         TopicName: CPEmailTask
         Subscription:
           - Protocol: Email
             Endpoint: REPLACE.EMAILADDRESS            

#DefinePlugins
plugins:
  - serverless-python-requirements

#Define Custom Parameters
custom:
 pythonRequirements:
   dockerizePip: non-linux
  
