name: 'CI/CD'
on:
  push:
    branches:
    - master
    paths:
    - '_destroy_flag'

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: .
     
    steps:
#Setup Environment
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

#Checkout code from repository
    - name: Checkout Code
      uses: actions/checkout@v1 

#Install Dependencies      
    - name: Install Relevant Plugins + Dependencies
      run: |
          npm install -g serverless 

#Configure AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

# Insert Secrets into serverless.yml
    - name: Insert Secrets
      run: |
          sed -i "/Endpoint/c\    Endpoint\ : \"${{ secrets.EMAIL }}\"" serverless.yml
          sed -i "/MGMTHOSTNAME/c\      MGMTHOSTNAME\ : \"${{ secrets.MGMTHOSTNAME }}\"" serverless.yml
          sed -i "/USER/c\      USER\ : \"${{ secrets.USER }}\"" serverless.yml
          sed -i "/PASSWORD/c\      PASSWORD\ : \"${{ secrets.PASSWORD }}\"" serverless.yml

#Deploy function to AWS       
    - name: Deploy to AWS
      run: |
        pip install awscli 
        sls remove 
      timeout-minutes: 30
      continue-on-error: true
   
